Alteração em dadosCadastrais e 2 novas páginas
MatheusRomeike/picareta-leiloes pull request #2
Opened 2023-04-03 03:04 UTC by abressam

Foi feito o método GET no formulário de dados cadastrais e criadas as páginas de contato e eventos.

2023-04-03 17:14 UTC, MatheusRomeike commented
Não é assim que o método GET funciona, o formulário é um POST pois envia dados para serem salvos, GET é quando queremos pesquisar algo. O GET dessa tela vai ocorrer direto no php, não no formulário.

2023-04-03 17:27 UTC, MatheusRomeike requested changes

2023-04-03 17:27 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastrais.php
> -        <div class="left">
sidebar faz parte da área do usuário logado

2023-04-03 17:27 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
não é assim que o GET funciona
https://www.alura.com.br/artigos/diferencas-entre-get-e-post

2023-04-03 17:27 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastrais.php
> +                        <input type="text" id="cpf" name="CPF" maxLength="14" class="form-control" placeholder="CPF*" onblur="validateInput(this)" required>
name é dispensável quando usamos o id

2023-04-03 17:27 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastrais.php
> +                        <select class="form-select" id="maritalStatus" name="Estado Civil" onchange="validateInput(this)" required>
onblur valida melhor que onchange, já que pega o click até sem selecionar nada

2023-04-03 17:27 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastrais.php
> +                            <option value="Masculino">Masculino</option>
valores assim são salvos como small int no banco, então mantem os números por desempenho da aplicação
(Tem um dicionario nas tabelas do banco)

2023-04-03 17:27 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastraisAction.php
> +    <title>Dados Cadastrais Registrados</title>
Não faz sentido ficar separando crud, é mais usável você carregar os dados do banco na outra tela e editar por lá

2023-04-03 17:32 UTC, MatheusRomeike requested changes

2023-04-03 17:32 UTC, MatheusRomeike commented on pages/eventos/eventos.php
> +                        <p class='card-text'>Rua Lodovico Geronazzo, 525 - Boa Vista, Curitiba.</p>
https://www.claudiokussleiloes.com.br/proximos-leiloes
o formato é esse, sem endereços diferentes, a picareta leilões tem um pátio fixo
da pra usar até a grid dinamica para abrir a listagem de lotes

2023-04-03 19:14 UTC, abressam commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
Só fiz desse formato porque a Cristine me questionou, já que após clicar no botão "Salvar" a tela não estava sendo redirecionada para outro canto com os dados inseridos pelo usuário. Por isso também que adicionei o name em cada input, pra pegar os valores na URL. Eu entendo que claramente não é o ideal mas segue o padrão que ela quer para a primeira entrega, então vamos ter que avaliar isso: https://pucpr.instructure.com/courses/19610/pages/ec-isi-aula3-regex-+-js?module_item_id=457034

2023-04-03 19:15 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
isso só não faz sentido, um form de submeter dados ser um get

2023-04-03 19:24 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
acho que o ideal pra essa situação é mockar os dados, já que não temos conexão com o banco ainda e a primeira entrega é só front

2023-04-03 22:50 UTC, abressam commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
Porque só fiz do jeito dela pra mostar na apresentação tipo "está aqui o jeito que você pediu", porque com certeza isso vai ser mudado depois na Sprint 2. Eu também nunca vi um enviar dados de um formulário através de um get. Só to preocupada com esse négocio aqui: 

6. É possível visualizar o preenchimento dos dados nos campos de entrada, em uma nova página web no front-end (ex. nova página HTML apresenta os dados de um formulário, após a submissão via **method=GET**).

2023-04-03 22:51 UTC, abressam commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
Acredito que ela quer assim justamente por ser só front essa entrega.

2023-04-03 23:04 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
esse 6 já foi resolvido nos outros cruds, não precisa ser necessariamente nessa tela. e esse get tem 0 sentido,

2023-04-03 23:27 UTC, abressam commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
![image](https://user-images.githubusercontent.com/71531467/229647822-46711abc-5b93-48dc-98f7-cb1ba03bdffa.png)

![image](https://user-images.githubusercontent.com/71531467/229648082-07927d02-a8dd-492d-bba2-bc43320a7bac.png)


Ok, mas ta sendo feito um GET literalmente com o nome "post" na URL, isso faz sentido?

2023-04-03 23:31 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
vão ter as duas requisições na mesma, esse requisito 6 ficou nos cruds

2023-04-03 23:32 UTC, abressam commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
Sim, mas é igual você disse não está desenvolvido e a entrega dessa Sprint é front e não back.

2023-04-03 23:35 UTC, MatheusRomeike commented on pages/dadosCadastrais/dadosCadastrais.php
> +            <form class="row d-flex justify-content-center" id="form" method="GET" action="dadosCadastraisAction.php">
requisições fazem parte do back,.não do front zzzzz

2023-04-04 04:11 UTC, abressam commented
Deletei os arquivos de dadosCadastrais que eu havia modificado. Adicionei botões em cada card do evento que devem enviar para a página correspondente da listagem quando for feita. Também adicionei duas classes do bootstrap no footer para tentar arrumar a altura quando a tela é menor.

2023-04-04 13:26 UTC, merged